"""5분봉 횡보장 박스 / 중립장 MACD+RSI 스캘핑 설정."""

# 거래
SYMBOL = "BTC/USDT"
TIMEFRAME = "5m"

# 포지션
LEVERAGE = 6
POSITION_SIZE_PERCENT = 0.25
FEE_RATE = 0.001
SLIPPAGE_PCT = 0.05

# 지표
RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
MA_SHORT_PERIOD = 7
MA_LONG_PERIOD = 20
MA_MID_PERIOD = 50
MA_LONGEST_PERIOD = 100

# 장세 (15분봉 24h)
REGIME_LOOKBACK_15M = 96

# 중립장 (횡보 아님) - MACD+RSI 진입
NEUTRAL_RSI_LONG_MAX = 30   # RSI ≤ 30 → 롱
NEUTRAL_RSI_SHORT_MIN = 70  # RSI ≥ 70 → 숏
NEUTRAL_PROFIT_TARGET = 4.0
NEUTRAL_STOP_LOSS = 3.0
NEUTRAL_STOP_LOSS_PRICE = 3.0

# 횡보장 박스
SIDEWAYS_ENABLED = True
SIDEWAYS_BOX_PERIOD = 48
SIDEWAYS_BOX_TOP_MARGIN = 0.04
SIDEWAYS_BOX_BOTTOM_MARGIN = 0.04
SIDEWAYS_MIN_TOUCHES = 2
SIDEWAYS_BOX_RANGE_PCT_MIN = 1.5
SIDEWAYS_PROFIT_TARGET = 2.5
SIDEWAYS_STOP_LOSS = 2.0
SIDEWAYS_STOP_LOSS_PRICE = 2.0
SIDEWAYS_BOX_EXIT_MARGIN_PCT = 1.5

# 손실 한도
DAILY_LOSS_LIMIT_PCT = 5.0
CONSECUTIVE_LOSS_LIMIT = 4

# 백테스트
INITIAL_BALANCE = 1000.0
