"""공통 전략/지표 설정. config_paper / config_live 에서 import 후 필요 시 override."""

# 거래
SYMBOL = "BTC/USDT"
TIMEFRAME = "5m"

# 포지션 (paper/live에서 override 가능)
LEVERAGE = 6
POSITION_SIZE_PERCENT = 0.25
FEE_RATE = 0.001
SLIPPAGE_PCT = 0.05

# 지표
RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
MA_SHORT_PERIOD = 7
MA_LONG_PERIOD = 20
MA_MID_PERIOD = 50
MA_LONGEST_PERIOD = 100

# 장세 (15분봉 24h)
REGIME_LOOKBACK_15M = 96

# 추세장
TREND_PROFIT_TARGET = 5.0
TREND_STOP_LOSS = 2.5
TREND_STOP_LOSS_PRICE = 2.5
TREND_PULLBACK_MA_PCT = 1.0
TREND_RSI_LONG_MAX = 58
TREND_RSI_SHORT_MIN = 42
TREND_MA50_MA100_FILTER = True

# 횡보장 박스
SIDEWAYS_ENABLED = True
SIDEWAYS_BOX_PERIOD = 48
SIDEWAYS_BOX_TOP_MARGIN = 0.04
SIDEWAYS_BOX_BOTTOM_MARGIN = 0.04
SIDEWAYS_MIN_TOUCHES = 2
SIDEWAYS_BOX_RANGE_PCT_MIN = 1.5
SIDEWAYS_BOX_RANGE_MIN = 1  # 횡보장 상단-하단 봉간격 최소 (절대값)
SIDEWAYS_PROFIT_TARGET = 2.5
SIDEWAYS_STOP_LOSS = 2.0
SIDEWAYS_STOP_LOSS_PRICE = 2.0
SIDEWAYS_BOX_EXIT_MARGIN_PCT = 0.5  # 박스 상·하단 돌파(이탈) 기준: 가격이 상단/하단에서 0.5% 벗어나면 이탈

# 손실 한도 (paper/live에서 override 가능)
DAILY_LOSS_LIMIT_PCT = 5.0
CONSECUTIVE_LOSS_LIMIT = 4

# 백테스트/페이퍼 전용
INITIAL_BALANCE = 1000.0
